###
### Liquibase version: 4.30.0+
###
### Liquibase sales: https://www.liquibase.com/contact-us
### Liquibase support: https://support.liquibase.com
###

###
### Flow documentation: https://docs.liquibase.com/commands/flow/flow.html
###

###
### Global variables used in the flowfile
###
globalVariables:

###
### Stages to execute
###
stages:
  Default:
    actions:
      #
      # Validate database connection
      # https://docs.liquibase.com/commands/change-tracking/connect.html
      #
      - type: liquibase
        command: connect
      #
      # View pending changes
      # https://docs.liquibase.com/commands/change-tracking/status.html
      #
      - type: liquibase
        command: status
      #
      # Exit if no pending changes
      # https://docs.liquibase.com/liquibase-pro/flow/home.html
      #
      - type: control
        if: "status.changesetCount == 0"
        command: exit
        cmdArgs: { exitCode: "0", exitMessage: "Database is current!" }
      #
      # Update database
      # https://docs.liquibase.com/commands/update/update.html
      #
      - type: liquibase
        command: update
        cmdArgs: { report-enabled: "true" }
        globalArgs: { reports-open: "false" }

###
### Always execute
###
endStage:
  actions:
    #
    # Show deployed changes
    # https://docs.liquibase.com/commands/change-tracking/history.html
    #
    - type: liquibase
      command: history